services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:24-trixie
    command: sleep infinity
    user: node
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/workspaces:cached
      - pnpm_store:/home/node/.pnpm-store

volumes:
  pnpm_store:
